schema:
  instanceName: sars_cov-2_minimal_test_config
  metadata:
    - name: primary_key
      type: string
    - name: usherTree
      type: string
      isPhyloTreeField: true
    - name: date
      type: date
    - name: unsorted_date
      type: date
    - name: region
      type: string
      generateIndex: true
    - name: country
      type: string
    - name: pango_lineage
      type: string
      generateIndex: true
      generateLineageIndex: lineage_definition.yaml
    - name: division
      type: string
      generateIndex: true
    - name: age
      type: int
    - name: qc_value
      type: float
    - name: test_boolean_column
      type: boolean
  primaryKey: primary_key
defaultNucleotideSequence: "main"
